language: scala
scala:
- 2.10.3
env:
  global:
    secure: Lb+lNIbdQagnYVhOrNES9F4Or/42T8+NaaEfF+ODkyn8sG1moFELCDgmICJCO+2ZxNkWtv0sxzptenG174sXeXELWzTfTPSNVhbj8PizGPpnPj3aeuMKTRC/+uRMhMaFjp/h9SSlYsoog3KrY8FA22ksIx5QbiGzwgL5M9AM1E4=
script: sbt coveralls package
after_success: sbt deploy
